In [2]:

def test():
    print("test()for function")
    return
test()

test()for function


In [3]:
class demo:
    def test(self):
        print("test()for the class and method")
        return
obj=demo()
obj.test()

test()for the class and method


In [4]:
class demo1:
    def fact(self,n):
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=demo1()
print(p1.fact(5))

120


In [5]:
# Sites Inheritance
class person():
    def __init__(self,name):
        self.name=name
    def getName(self):
        return self.name
    def isEmployee(self):
        return False
## Derived CLass 
class Employee(person):
    def isEmployee(self):
        return True
emp = person("Anil")
emp2=Employee("Mahesh")
emp1 = person("Vamsi ")
print(emp.getName(),emp.isEmployee())
print(emp1.getName(),emp1.isEmployee())
emp = person("Akhil")
print(emp.getName(),emp.isEmployee())
print(emp2.getName(),emp2.isEmployee())

Anil False
Vamsi  False
Akhil False
Mahesh True


In [1]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(lst)


[1, 2, 3, 4]


In [2]:
lst= [1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int32


In [3]:
a1 = np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
a1= np.array([1,2,3])
a2= np.array([4,5,6])
print(np.hstack((a1,a2)))


[1 2 3 4 5 6]


In [10]:
# import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [3]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [5]:

al=np.array([(1,2,3),(4,5,6)])
print("sliceing last colum",al[:,2])

sliceing last colum [3 6]


In [7]:
import pandas as pd
dict ={"Name":["Akash","Anil","DInesh","Harshith","Ajay","Kranth"],
       "EmailID=":["akash@gmail.com","Anil@gmail.com","dinesh@gmail.com","harsha@gmail.com","Ajay@gmail.com","Kranth@gmail.com"],
       "MobileNumber":[999,888,777,666,555,444],
       "Address":["Hyd","Hyd","Hyd","hyd","Hyd","Hyd"] }
b=pd.DataFrame(dict)
b.index=["01","02","03","04","05","06"]
print(b)



        Name          EmailID=  MobileNumber Address
01     Akash   akash@gmail.com           999     Hyd
02      Anil    Anil@gmail.com           888     Hyd
03    DInesh  dinesh@gmail.com           777     Hyd
04  Harshith  harsha@gmail.com           666     hyd
05      Ajay    Ajay@gmail.com           555     Hyd
06    Kranth  Kranth@gmail.com           444     Hyd


In [3]:
def check(s1, s2): 
    if(sorted(s1)== sorted(s2)): 
        print("The strings are anagrams.")  
    else: 
        print("The strings aren't anagrams.")          
          
# driver code   
s1 ="listen"
s2 ="silent" 
check(s1, s2) 

The strings are anagrams.
